changelog:
  categories:
    - title: "🎉 New Features"
      labels:
        - "type: feature"

    - title: "❤️ Improvements"
      labels:
        - "type: enhancement"

    - title: "🛠️ Bugfixes"
      labels:
        - "type: bug"
