query GetVersionsByProductId(
  $projectName: String!
  $productIds: [String!]!
  $versionFilter: String
  $taskFilter: String
  $folderFilter: String
  $featuredOnly: [String!]
  $featuredOnlyEntityType: String
  $hasReviewables: Boolean
  $sortBy: String
  $first: Int
  $last: Int
  $after: String
  $before: String
  $showComments: Boolean! = false
) {
  project(name: $projectName) {
    versions(
      productIds: $productIds
      filter: $versionFilter
      taskFilter: $taskFilter
      folderFilter: $folderFilter
      featuredOnly: $featuredOnly
      featuredOnlyEntityType: $featuredOnlyEntityType
      hasReviewables: $hasReviewables
      sortBy: $sortBy
      last: $last
      first: $first
      after: $after
      before: $before
    ) {
      pageInfo {
        ...PageInfo
      }
      edges {
        cursor
        node {
          ...VersionExtended
        }
      }
    }
  }
}
