// export all queries
export * from './actions'
export * from './activities'
export * from './addons'
export * from './attributes'
export * from './authentication'
export * from './cloud'
export * from './entities'
export * from './entityLists'
export * from './folders'
export * from './grouping'
export * from './links'
export * from './overview'
export * from './permissions'
export * from './products'
export * from './project'
export * from './review'
export * from './share'
export * from './system'
export * from './userDashboard'
export * from './users'
export * from './versions'
export * from './views'
export * from './watchers'
export * from './uris'

// re-export
export { confirmDialog } from 'primereact/confirmdialog'
