#import "./ProgressTaskFragment.graphql"

query GetTasksProgress(
  $projectName: String!
  $folderIds: [String!]
  $assignees: [String!]
  $assigneesAny: [String!]
  $tags: [String!]
  $tagsAny: [String!]
  $statuses: [String!]
  $taskTypes: [String!]
  $attributes: [AttributeFilterInput!]
  $first: Int = 100
  $after: String
) {
  project(name: $projectName) {
    name
    tasks(
      folderIds: $folderIds
      first: $first
      after: $after
      includeFolderChildren: true
      assignees: $assignees
      assigneesAny: $assigneesAny
      tags: $tags
      tagsAny: $tagsAny
      statuses: $statuses
      taskTypes: $taskTypes
      attributes: $attributes
    ) {
      edges {
        node {
          ...ProgressTaskFragment
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
