query GetProjectInbox(
  $projectName: String!
  $userName: String!
  $referenceTypes: [String!]
  $activityTypes: [String!]
  $filter: String
  $last: Int
  $cursor: String
) {
  project(name: $projectName) {
    activities(
      entityNames: [$userName]
      referenceTypes: $referenceTypes
      activityTypes: $activityTypes
      filter: $filter
      last: $last
      before: $cursor
    ) {
      pageInfo {
        hasPreviousPage
        startCursor
        endCursor
      }
      edges {
        cursor
        node {
          ...MessageFragment
        }
      }
    }
  }
}
