export default [
  {
    name: '2023.08.full',
    label: 'Full',
    bio: 'Not sure? Here is everything we think you will need',
    icon: 'done_all',
    createdAt: '2023-08-01T00:00:00.000Z',
    addons: [
      'core',
      'applications',
      'deadline',
      'maya',
      'nuke',
      'houdini',
      'blender',
      'aftereffects',
      'premiere',
      'photoshop',
      'illustrator',
      'substance',
      'zbrush',
      'fusion',
      'mari',
      'katana',
      'shotgrid',
      'ftrack',
      'rv',
      'flame',
      'resolve',
      'clarisse',
      'cinema4d',
      'clickup',
      'jira',
      'trello',
      'slack',
      'teams',
      'zoom',
    ],
  },
  {
    name: '2023.08.3D',
    label: '3D',
    bio: 'Workflows with softwares like Maya and Houdini',
    icon: 'deployed_code',
    createdAt: '2023-08-01T00:00:00.000Z',
    addons: [
      'core',
      'applications',
      'deadline',
      'maya',
      'houdini',
      'blender',
      'substance',
      'zbrush',
      'mari',
      'katana',
      'shotgrid',
      'ftrack',
      'clarisse',
      'cinema4d',
    ],
  },
  {
    name: '2023.08.2D',
    label: '2D',
    bio: 'Workflows with softwares like Photoshop and Illustrator',
    icon: '2d',
    createdAt: '2023-08-01T00:00:00.000Z',
    addons: [
      'core',
      'applications',
      'deadline',
      'photoshop',
      'illustrator',
      'premiere',
      'shotgrid',
      'ftrack',
      'resolve',
      'clickup',
      'jira',
      'trello',
      'slack',
      'teams',
      'zoom',
    ],
  },
  {
    name: '2023.08.VFX',
    label: 'VFX',
    bio: 'Workflows with softwares like Nuke and AfterEffects',
    icon: 'movie',
    createdAt: '2023-08-01T00:00:00.000Z',
    addons: [
      'core',
      'applications',
      'deadline',
      'nuke',
      'aftereffects',
      'shotgrid',
      'ftrack',
      'fusion',
      'rv',
      'flame',
      'clickup',
      'jira',
      'trello',
      'slack',
      'teams',
      'zoom',
    ],
  },
]
