// FIX: just place holder for now
const release = {
  name: '2023.08',
  addons: [
    {
      name: 'Core',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/core-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Deadline',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/deadline-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Maya',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/maya-1.0.0.zip',
      tags: ['full', '3D', 'vfx'],
    },
    {
      name: 'Nuke',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/nuke-1.0.0.zip',
      tags: ['full', 'vfx'],
    },
    {
      name: 'Houdini',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/houdini-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'Blender',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/blender-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'AfterEffects',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/aftereffects-1.0.0.zip',
      tags: ['full', 'vfx'],
    },
    {
      name: 'Premiere',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/premiere-1.0.0.zip',
      tags: ['full', '2D'],
    },
    {
      name: 'Photoshop',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/photoshop-1.0.0.zip',
      tags: ['full', '2D'],
    },
    {
      name: 'Illustrator',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/illustrator-1.0.0.zip',
      tags: ['full', '2D'],
    },
    {
      name: 'Substance',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/substance-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'Zbrush',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/zbrush-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'Fusion',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/fusion-1.0.0.zip',
      tags: ['full', 'vfx'],
    },
    {
      name: 'Mari',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/mari-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'Katana',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/katana-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'Shotgrid',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/shotgrid-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'ftrack',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/ftrack-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'RV',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/rv-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Flame',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/flame-1.0.0.zip',
      tags: ['full', 'vfx', '3D'],
    },
    {
      name: 'Resolve',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/resolve-1.0.0.zip',
      tags: ['full', '2D'],
    },
    {
      name: 'Clarisse',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/clarisse-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'Cinema4D',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/cinema4d-1.0.0.zip',
      tags: ['full', '3D'],
    },
    {
      name: 'ClickUp',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/clickup-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Jira',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/jira-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Trello',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/trello-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Slack',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/slack-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Teams',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/teams-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
    {
      name: 'Zoom',
      version: '1.0.0',
      url: 'https://get.ayon.io/addons/zoom-1.0.0.zip',
      tags: ['full', '2D', '3D', 'vfx'],
    },
  ],
  presets: [
    {
      name: 'Full Suite',
      tag: 'full',
      bio: 'Not sure? Here is everything we think you will need',
      icon: 'done_all',
    },
    {
      name: '3D',
      tag: '3D',
      bio: 'Workflows with softwares like Maya and Houdini',
      icon: 'deployed_code',
    },
    {
      name: '2D',
      tag: '2D',
      bio: 'Workflows with softwares like Photoshop and Illustrator',
      icon: '2d',
    },
    {
      name: 'VFX',
      tag: 'vfx',
      bio: 'Workflows with softwares like Nuke and AfterEffects',
      icon: 'movie',
    },
  ],
}

export default release
